export const data = [{
        id: 9,
        first_name: "Akshaya ",
        last_name: "Bala",
        email: "akshayabala@student.tce.edu",
        Dept: "IT",
        Hoursspent: "2",
        Logincount: "3",
    },

    {
        id: 4,
        first_name: "Adithi ",
        last_name: "mp",
        email: "adithimp@student.tce.edu",
        Dept: "IT",
        Hoursspent: "1",
        Logincount: "2",
    },

    {
        id: 3,
        first_name: "Abirami ",
        last_name: "s",
        email: "abis@student.tce.edu",
        Dept: "IT",
        Hoursspent: "2",
        Logincount: "4",
    },

    {
        id: 7,
        first_name: "Akchaya ",
        last_name: "",
        email: "akchaya@student.tce.edu",
        Dept: "IT",
        Hoursspent: "1",
        Logincount: "3",
    },

    {
        id: 12,
        first_name: "shrinithi ",
        last_name: "t",
        email: "shri@student.tce.edu",
        Dept: "ECE",
        Hoursspent: "1",
        Logincount: "4",
    },

    {
        id: 6,
        first_name: "Akash ",
        last_name: "Dharsan",
        email: "akash@student.tce.edu",
        Dept: "IT",
        Hoursspent: "1",
        Logincount: "1",
    },

    {
        id: 30,
        first_name: "Harini",
        last_name: "krishna",
        email: "harini@student.tce.edu",
        Dept: "IT",
        Hoursspent: "4",
        Logincount: "3",
    },

    {
        id: 66,
        first_name: "pooja ",
        last_name: "p",
        email: "pooja@student.tce.edu",
        Dept: "IT",
        Hoursspent: "3",
        Logincount: "4",
    },

    {
        id: 89,
        first_name: "Sarumathi ",
        last_name: "",
        email: "saru@student.tce.edu",
        Dept: "IT",
        Hoursspent: "5",
        Logincount: "6",
    },
    {
        id: 107,
        first_name: "Susmitha ",
        last_name: "ramesh",
        email: "susmi@student.tce.edu",
        Dept: "IT",
        Hoursspent: "4",
        Logincount: "3",
    },
    {
        id: 51,
        first_name: "Naga ",
        last_name: "Dharsan",
        email: "dharsan@student.tce.edu",
        Dept: "MECH",
        Hoursspent: "5",
        Logincount: "2",
    },
    {
        id: 52,
        first_name: "krishna ",
        last_name: "moorthy",
        email: "krishna@student.tce.edu",
        Dept: "CSE",
        Hoursspent: "2",
        Logincount: "3",
    },
    {
        id: 90,
        first_name: "sri ",
        last_name: "",
        email: "sri@student.tce.edu",
        Dept: "IT",
        Hoursspent: "2",
        Logincount: "3",
    },
    {
        id: 44,
        first_name: "Krishna",
        last_name: "Kumar",
        email: "krishna@student.tce.edu",
        Dept: "IT",
        Hoursspent: "2",
        Logincount: "3",
    },
    {
        id: 43,
        first_name: "Pravin ",
        last_name: "Balaji",
        email: "pravin@student.tce.edu",
        Dept: "IT",
        Hoursspent: "2",
        Logincount: "3",
    },
    {
        id: 2,
        first_name: "Akshaya ",
        last_name: "",
        email: "aksh@student.tce.edu",
        Dept: "ECE",
        Hoursspent: "2",
        Logincount: "3",
    },
    {
        id: 9,
        first_name: "Akshaya ",
        last_name: "Bala",
        email: "akshayabala@student.tce.edu",
        Dept: "IT",
        Hoursspent: "2",
        Logincount: "3",
    },
    {
        id: 70,
        first_name: "naveen ",
        last_name: "kumar",
        email: "naveen@student.tce.edu",
        Dept: "DS",
        Hoursspent: "5",
        Logincount: "4",
    },
    {
        id: 9,
        first_name: "raghuveer ",
        last_name: "",
        email: "ragu@student.tce.edu",
        Dept: "EEE",
        Hoursspent: "7",
        Logincount: "4",
    },

];